/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author phamn
 */
public class HeaderComponent extends javax.swing.JPanel {

    /**
     * Creates new form HeaderComponent
     */
    public HeaderComponent() {
        initComponents();
        LineBorder border=new LineBorder(Color.WHITE);
        color1.setOpaque(true);
        color1.setBorder(border);
        color2.setOpaque(true);
color2.setBorder(border);
        color3.setOpaque(true);
color3 .setBorder(border);
        color8.setOpaque(true);
        color8.setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        color4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        color5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        color6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        color1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        color2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        color3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        color8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Search:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 29, 188, -1));

        color4.setBackground(new java.awt.Color(0, 153, 0));
        color4.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(color4, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 29, -1, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Phòng trống");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 29, -1, -1));

        color5.setBackground(new java.awt.Color(204, 0, 51));
        color5.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(color5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 29, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setText("Có khách");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 29, -1, -1));

        color6.setBackground(new java.awt.Color(204, 204, 0));
        color6.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(color6, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 29, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setText("Đang dọn dẹp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 29, -1, -1));

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        color1.setBackground(new java.awt.Color(102, 255, 102));
        color1.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 20, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Phòng trống");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 100, -1));

        color2.setBackground(new java.awt.Color(255, 51, 51));
        color2.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 20, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("Có khách");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 70, -1));

        color3.setBackground(new java.awt.Color(153, 153, 153));
        color3.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(color3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 20, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Đang bảo trì");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 110, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setText("Đang dọn dẹp");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 110, -1));

        color8.setBackground(new java.awt.Color(255, 255, 0));
        color8.setForeground(new java.awt.Color(255, 255, 255));
        color8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(color8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel color1;
    private javax.swing.JLabel color2;
    private javax.swing.JLabel color3;
    private javax.swing.JLabel color4;
    private javax.swing.JLabel color5;
    private javax.swing.JLabel color6;
    private javax.swing.JLabel color8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
