/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ServiceDAO;
import dao.TypeOfServiceDAO;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import model.Service;
import model.TypeOfService;
import util.MsgBox;

/**
 *
 * @author ta2khu75
 */
public class ServiceFrm extends javax.swing.JPanel {

    int id = 0;
    private NumberFormat numberFormat = 
            NumberFormat.getCurrencyInstance(new Locale("vi","VN"));

    /**
     * Creates new form JPanel
     */
    public ServiceFrm() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNameService = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnInsertService = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();
        btnUpdateService = new javax.swing.JButton();
        btnNewService = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        cboType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnInsertType = new javax.swing.JButton();
        btnDeleteType = new javax.swing.JButton();
        btnUpdateType = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblType = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNameType = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(0, 689));

        jLabel3.setText("Loại dịch vụ:");

        jLabel4.setText("Tên dịch vụ:");

        jLabel5.setText("Đơn giá:");

        btnInsertService.setBackground(new java.awt.Color(153, 255, 153));
        btnInsertService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertService.setForeground(new java.awt.Color(0, 0, 0));
        btnInsertService.setText("Thêm");
        btnInsertService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertServiceActionPerformed(evt);
            }
        });

        btnDeleteService.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteService.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteService.setText("Xóa");
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });

        btnUpdateService.setBackground(new java.awt.Color(204, 204, 0));
        btnUpdateService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateService.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateService.setText("Sửa");
        btnUpdateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateServiceActionPerformed(evt);
            }
        });

        btnNewService.setBackground(new java.awt.Color(0, 204, 204));
        btnNewService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNewService.setForeground(new java.awt.Color(0, 0, 0));
        btnNewService.setText("Mới");
        btnNewService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewServiceActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblService.setAutoCreateRowSorter(true);
        tblService.setBackground(new java.awt.Color(255, 255, 255));
        tblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblService.setForeground(new java.awt.Color(0, 0, 0));
        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên mã dịch vụ", "Tên loại dịch vụ", "Đơn giá"
            }
        ));
        tblService.setFocusable(false);
        tblService.setGridColor(new java.awt.Color(230, 230, 230));
        tblService.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblService.setRowHeight(40);
        tblService.setShowHorizontalLines(true);
        tblService.getTableHeader().setReorderingAllowed(false);
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblService);

        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNameService, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInsertService)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteService)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateService)
                .addGap(18, 18, 18)
                .addComponent(btnNewService)
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNameService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertService)
                    .addComponent(btnDeleteService)
                    .addComponent(btnUpdateService)
                    .addComponent(btnNewService))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Dịch vụ", jPanel2);

        btnInsertType.setText("Thêm");
        btnInsertType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertTypeActionPerformed(evt);
            }
        });

        btnDeleteType.setText("Xóa");
        btnDeleteType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTypeActionPerformed(evt);
            }
        });

        btnUpdateType.setText("Sửa");
        btnUpdateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTypeActionPerformed(evt);
            }
        });

        jButton8.setText("Mới");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblType.setAutoCreateRowSorter(true);
        tblType.setBackground(new java.awt.Color(255, 255, 255));
        tblType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblType.setForeground(new java.awt.Color(0, 0, 0));
        tblType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ));
        tblType.setFocusable(false);
        tblType.setGridColor(new java.awt.Color(230, 230, 230));
        tblType.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblType.setRowHeight(40);
        tblType.setShowHorizontalLines(true);
        tblType.getTableHeader().setReorderingAllowed(false);
        tblType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTypeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblType);

        jLabel6.setText("  Mã loại");

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Tên dịch vụ:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNameType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(btnInsertType)
                            .addGap(18, 18, 18)
                            .addComponent(btnDeleteType)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdateType)
                            .addGap(18, 18, 18)
                            .addComponent(jButton8))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNameType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertType)
                    .addComponent(btnDeleteType)
                    .addComponent(btnUpdateType)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại dịch vụ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseClicked
        // TODO add your handling code here:
        Service service = serviceList.get(tblService.getSelectedRow());
        id = service.getId();
        txtNameService.setText(service.getName());
        txtPrice.setText(service.getPrice() + "");
        for (TypeOfService x : typeList) {
            if (x.getId().equals(service.getIdTypeOfService())) {
                cboType.setSelectedItem(x.getName());
                return;
            }
        }
    }//GEN-LAST:event_tblServiceMouseClicked

    private void tblTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTypeMouseClicked
        // TODO add your handling code here:
        TypeOfService service = typeList.get(tblType.getSelectedRow());
        txtType.setText(service.getId());
        txtNameType.setText(service.getName());
    }//GEN-LAST:event_tblTypeMouseClicked

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnInsertServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertServiceActionPerformed
        // TODO add your handling code here:
        Service service = checkService();
        if (service != null) {
            serviceDAO.insert(service);
            MsgBox.showMessage(this, "Thêm thành công");
            fillTblService();
        }
    }//GEN-LAST:event_btnInsertServiceActionPerformed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
        // TODO add your handling code here:
        Service service = checkService();
        if (service != null && id != 0) {
            service.setId(id);
            serviceDAO.delete(service);
            MsgBox.showMessage(this, "Xóa thành công");
            fillTblService();
        }
    }//GEN-LAST:event_btnDeleteServiceActionPerformed

    private void btnUpdateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateServiceActionPerformed
        // TODO add your handling code here:
        Service service = checkService();
        if (service != null) {
            service.setId(id);
            serviceDAO.update(service);
            MsgBox.showMessage(this, "Cập nhập thành công");
            fillTblService();
        }
    }//GEN-LAST:event_btnUpdateServiceActionPerformed

    private void btnInsertTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertTypeActionPerformed
        // TODO add your handling code here:
        TypeOfService service = checkType();
        if (service != null) {
            typeDAO.insert(service);
            MsgBox.showMessage(this, "Thêm thành công");
            fillTblType();
        }
    }//GEN-LAST:event_btnInsertTypeActionPerformed

    private void btnDeleteTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTypeActionPerformed
        // TODO add your handling code here:
        TypeOfService service = checkType();
        if (service != null) {
            typeDAO.delete(service);
            MsgBox.showMessage(this, "Thêm thành công");
            fillTblType();
        }
    }//GEN-LAST:event_btnDeleteTypeActionPerformed

    private void btnUpdateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTypeActionPerformed
        // TODO add your handling code here:
        TypeOfService service = checkType();
        if (service != null) {
            typeDAO.update(service);
            MsgBox.showMessage(this, "Cập nhập thành công");
            fillTblType();
        }
    }//GEN-LAST:event_btnUpdateTypeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        cleanType();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnNewServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewServiceActionPerformed
        // TODO add your handling code here:
        cleanService();
    }//GEN-LAST:event_btnNewServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnDeleteType;
    private javax.swing.JButton btnInsertService;
    private javax.swing.JButton btnInsertType;
    private javax.swing.JButton btnNewService;
    private javax.swing.JButton btnUpdateService;
    private javax.swing.JButton btnUpdateType;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblService;
    private javax.swing.JTable tblType;
    private javax.swing.JTextField txtNameService;
    private javax.swing.JTextField txtNameType;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelService;
    private DefaultTableModel modelType;
    private ServiceDAO serviceDAO = new ServiceDAO();
    private TypeOfServiceDAO typeDAO = new TypeOfServiceDAO();
    private List<Service> serviceList;
    private List<TypeOfService> typeList;

    private void init() {
        modelService = (DefaultTableModel) tblService.getModel();
        modelType = (DefaultTableModel) tblType.getModel();
        fillTblType();
        fillTblService();
    }

    private void fillTblService() {
        serviceList = serviceDAO.selectAll();
        modelService.setRowCount(0);
        typeList = typeDAO.selectAll();
        for (Service x : serviceList) {
            for (TypeOfService y : typeList) {
                if (y.getId().equals(x.getIdTypeOfService())) {
                    System.out.println("s");
                    modelService.addRow(new Object[]{
                        x.getId(), x.getName(), y.getName(), numberFormat.format(x.getPrice())
                    });
                }
            }
        }
        modelService.fireTableDataChanged();
        cleanService();
    }

    private void fillTblType() {
        typeList = typeDAO.selectAll();
        modelType.setRowCount(0);
        for (TypeOfService x : typeList) {
            modelType.addRow(new Object[]{
                x.getId(), x.getName()
            });
        }
        modelType.fireTableDataChanged();
        fillCboType();
        cleanType();
    }

    private void fillCboType() {
        cboType.removeAllItems();
        for (TypeOfService x : typeList) {
            cboType.addItem(x.getName());
        }
    }

    private TypeOfService checkType() {
        String Id = txtType.getText();
        String name = txtNameType.getText();
        if (Id.isEmpty() || name.isEmpty()) {
            MsgBox.showMessage(this, "Vui lòng nhập đầy đủ thông tin");
            return null;
        }
        return new TypeOfService(Id, name);
    }

    private Service checkService() {
        String name = txtNameService.getText();
        String price = txtPrice.getText();
        if (name.isEmpty() || price.isEmpty()) {
            MsgBox.showMessage(this, "Vui lòng nhập đầy đủ thông tin");
            return null;
        }
        float pric = 0;
        try {
            pric = Float.parseFloat(price);
        } catch (Exception e) {
            MsgBox.showMessage(this, "Đơn giá phải là số ");
            return null;
        }

        return new Service(name, pric, typeList.get(cboType.getSelectedIndex()).getId());
    }

    private void cleanService() {
        txtPrice.setText("");
        txtNameService.setText("");
    }

    private void cleanType() {
        txtType.setText("");
        txtNameType.setText("");
    }
}
