/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.StatisticalDAO;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import util.Auth;
import util.ExportExcel;
import util.MsgBox;
import util.XDate;

/**
 *
 * @author phamn
 */
public class StaticticalFrm extends javax.swing.JPanel {
    private List<Object[]> listRevenues = new ArrayList<>();
    private List<Object[]> listGuest = new ArrayList<>();
    private List<Object[]> listService = new ArrayList<>();
    private StatisticalDAO dao = new StatisticalDAO();
     private NumberFormat numberFormat = 
            NumberFormat.getCurrencyInstance(new Locale("vi","VN"));
    /**
     * Creates new form StaticticalFrm
     */
    public StaticticalFrm() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSortService = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtSearchService = new javax.swing.JTextField();
        btnSearchService = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rdoDESC = new javax.swing.JRadioButton();
        rdoASC = new javax.swing.JRadioButton();
        btnRefreshService = new javax.swing.JButton();
        btnExportExcelService = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGuest = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtSearchGuest = new javax.swing.JTextField();
        btnSearchGuest = new javax.swing.JButton();
        btnRefreshGuest = new javax.swing.JButton();
        btnExportExcelGuest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chsFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chsTo = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnViewChart = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRevenue = new javax.swing.JTable();
        btnRefreshRevenue = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(0, 689));

        tabs.setPreferredSize(new java.awt.Dimension(0, 689));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblService.setAutoCreateRowSorter(true);
        tblService.setBackground(new java.awt.Color(255, 255, 255));
        tblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblService.setForeground(new java.awt.Color(0, 0, 0));
        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên dịch vụ", "Số lần sử dụng"
            }
        ));
        tblService.setFocusable(false);
        tblService.setGridColor(new java.awt.Color(230, 230, 230));
        tblService.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblService.setRowHeight(40);
        tblService.setShowHorizontalLines(true);
        tblService.getTableHeader().setReorderingAllowed(false);
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblService);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm theo tên"));

        txtSearchService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchServiceKeyPressed(evt);
            }
        });

        btnSearchService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchService.setText("Tìm");
        btnSearchService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSearchService, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchService)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchService, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchService))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));

        rdoDESC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoDESC.setText("Giảm dần");
        rdoDESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDESCActionPerformed(evt);
            }
        });

        rdoASC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoASC.setText("Tăng dần");
        rdoASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoASCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(rdoASC)
                .addGap(24, 24, 24)
                .addComponent(rdoDESC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoASC)
                    .addComponent(rdoDESC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRefreshService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnRefreshService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshServiceActionPerformed(evt);
            }
        });

        btnExportExcelService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExportExcelService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExportExcelService.setText("Xuất");
        btnExportExcelService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportExcelService, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshService, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExportExcelService)
                        .addComponent(btnRefreshService, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabs.addTab("Dịch vụ", jPanel1);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblGuest.setAutoCreateRowSorter(true);
        tblGuest.setBackground(new java.awt.Color(255, 255, 255));
        tblGuest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblGuest.setForeground(new java.awt.Color(0, 0, 0));
        tblGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số lần đặt phòng"
            }
        ));
        tblGuest.setFocusable(false);
        tblGuest.setGridColor(new java.awt.Color(230, 230, 230));
        tblGuest.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblGuest.setRowHeight(40);
        tblGuest.setShowHorizontalLines(true);
        tblGuest.getTableHeader().setReorderingAllowed(false);
        tblGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuestMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGuest);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm theo tên"));

        txtSearchGuest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchGuest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchGuestKeyPressed(evt);
            }
        });

        btnSearchGuest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchGuest.setText("Tìm");
        btnSearchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchGuest)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSearchGuest)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSearchGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        btnRefreshGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnRefreshGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshGuestActionPerformed(evt);
            }
        });

        btnExportExcelGuest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExportExcelGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExportExcelGuest.setText("Xuất");
        btnExportExcelGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnExportExcelGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRefreshGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExportExcelGuest)
                            .addComponent(btnRefreshGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabs.addTab("Khách hàng", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 689));

        chsFrom.setDateFormatString("dd/MM/yyyy");
        chsFrom.setMinSelectableDate(new java.util.Date(-62135791106000L));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Từ ngày:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Đến ngày:");

        chsTo.setDateFormatString("dd/MM/yyyy");
        chsTo.setMinSelectableDate(new java.util.Date(-62135791106000L));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnViewChart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bar-chart.png"))); // NOI18N
        btnViewChart.setText("Xem biểu đồ doanh thu từng năm");
        btnViewChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChartActionPerformed(evt);
            }
        });

        btnExportExcel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExportExcel.setText("Xuất");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblRevenue.setAutoCreateRowSorter(true);
        tblRevenue.setBackground(new java.awt.Color(255, 255, 255));
        tblRevenue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblRevenue.setForeground(new java.awt.Color(0, 0, 0));
        tblRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ngày", "Số khách hàng", "Doanh thu"
            }
        ));
        tblRevenue.setFocusable(false);
        tblRevenue.setGridColor(new java.awt.Color(230, 230, 230));
        tblRevenue.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblRevenue.setRowHeight(40);
        tblRevenue.setShowHorizontalLines(true);
        tblRevenue.getTableHeader().setReorderingAllowed(false);
        tblRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRevenueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRevenue);

        btnRefreshRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnRefreshRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(chsFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chsTo, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(733, Short.MAX_VALUE)
                        .addComponent(btnViewChart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefreshRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefreshRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chsFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1))
                    .addComponent(chsTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportExcel)
                    .addComponent(btnViewChart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabs.addTab("Doanh thu", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (chsFrom.getDate() == null || chsTo.getDate() == null) {
            MsgBox.showMessage(this, "Vui lòng chọn ngày");
            return;
        } else {
            SimpleDateFormat dateFormat =new SimpleDateFormat("yyyy/MM/dd");
                listRevenues.clear();
                listRevenues = dao.getRevenueByFromToDate(
                        dateFormat.format(chsFrom.getDate()),
                        dateFormat.format(chsTo.getDate()));
            
            
            showRevenues(listRevenues);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChartActionPerformed
        // TODO add your handling code here:
        showTotalRevenue();
    }//GEN-LAST:event_btnViewChartActionPerformed

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // TODO add your handling code here:
        ExportExcel.exportExcel(this, tblRevenue, "Doanhthu");
    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void tblRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRevenueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRevenueMouseClicked

    private void tblGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuestMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGuestMouseClicked

    private void tblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblServiceMouseClicked

    private void btnSearchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGuestActionPerformed
        // TODO add your handling code here:
         searchGuest();
    }//GEN-LAST:event_btnSearchGuestActionPerformed

    private void btnSearchServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchServiceActionPerformed
        // TODO add your handling code here:
        searchService("DESC");
    }//GEN-LAST:event_btnSearchServiceActionPerformed

    private void txtSearchServiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchServiceKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchService("DESC");
        }
    }//GEN-LAST:event_txtSearchServiceKeyPressed

    private void rdoASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoASCActionPerformed
        // TODO add your handling code here:
        searchService("ASC");
    }//GEN-LAST:event_rdoASCActionPerformed

    private void rdoDESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDESCActionPerformed
        // TODO add your handling code here:
        searchService("DESC");
    }//GEN-LAST:event_rdoDESCActionPerformed

    private void btnRefreshServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshServiceActionPerformed
        // TODO add your handling code here:
            listService.clear();
            listService = dao.getService("","desc");
            showService(listService);
    }//GEN-LAST:event_btnRefreshServiceActionPerformed

    private void btnRefreshRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshRevenueActionPerformed
        // TODO add your handling code here:
        listRevenues.clear();
        listRevenues = dao.getRevenueByDate("");
        showRevenues(listRevenues);
    }//GEN-LAST:event_btnRefreshRevenueActionPerformed

    private void btnRefreshGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshGuestActionPerformed
        // TODO add your handling code here:
        listGuest.clear();
        listGuest = dao.getGuest("");
        showGuest(listGuest);
    }//GEN-LAST:event_btnRefreshGuestActionPerformed

    private void btnExportExcelGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelGuestActionPerformed
        // TODO add your handling code here:
        ExportExcel.exportExcel(this, tblGuest, "KhachHang");
    }//GEN-LAST:event_btnExportExcelGuestActionPerformed

    private void btnExportExcelServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelServiceActionPerformed
        // TODO add your handling code here:
        ExportExcel.exportExcel(this, tblService, "DichVu");
    }//GEN-LAST:event_btnExportExcelServiceActionPerformed

    private void txtSearchGuestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchGuestKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchGuest();
        }
    }//GEN-LAST:event_txtSearchGuestKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnExportExcelGuest;
    private javax.swing.JButton btnExportExcelService;
    private javax.swing.JButton btnRefreshGuest;
    private javax.swing.JButton btnRefreshRevenue;
    private javax.swing.JButton btnRefreshService;
    private javax.swing.JButton btnSearchGuest;
    private javax.swing.JButton btnSearchService;
    private javax.swing.JButton btnViewChart;
    private javax.swing.ButtonGroup buttonGroupSortService;
    private com.toedter.calendar.JDateChooser chsFrom;
    private com.toedter.calendar.JDateChooser chsTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rdoASC;
    private javax.swing.JRadioButton rdoDESC;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblGuest;
    private javax.swing.JTable tblRevenue;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField txtSearchGuest;
    private javax.swing.JTextField txtSearchService;
    // End of variables declaration//GEN-END:variables

    private void init() {
        buttonGroupSortService.add(rdoASC);
        buttonGroupSortService.add(rdoDESC);
        rdoDESC.setSelected(true);
        listRevenues = dao.getRevenueByDate("");
        listService = dao.getService("", "DESC");
        listGuest = dao.getGuest("");
        showRevenues(listRevenues);
        showService(listService);
        showGuest(listGuest);
        if (!Auth.isManager()) {
            tabs.remove(2);
        }
    }
    public void showRevenues(List<Object[]> list) {
        DefaultTableModel tableModel = (DefaultTableModel) tblRevenue.getModel();
        tableModel.setRowCount(0);
        for (Object[] objects : list) {
            tableModel.addRow(new Object[]{XDate.toString((Date) objects[0], "dd/MM/yyyy"),objects[1],numberFormat.format(objects[2])});
        }
    }
    private void showTotalRevenue() {
         DefaultCategoryDataset dataset = new DefaultCategoryDataset();
         List<Object[]> l = dao.getTotalRevenueByYear();
        for (Object[] o : l) {
            dataset.addValue((double) o[2],"Năm", (Comparable) o[0]);
        }
        JFreeChart barChart = ChartFactory.createBarChart3D(
            "BIỂU ĐỒ DOANH THU THEO TỪNG NĂM",
            "Năm","Doanh thu",
            dataset,
            PlotOrientation.VERTICAL, false, false, false);
        ChartFrame frame = new ChartFrame("Biểu đồ tổng doanh thu", barChart);
        frame.setSize(1280,680);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private void showService(List<Object[]> listService) {
        DefaultTableModel tableModel = (DefaultTableModel) tblService.getModel();
        tableModel.setRowCount(0);
        for (Object[] objects : listService) {
            tableModel.addRow(new Object[]{objects[0],objects[1]});
        }
    }

    private void searchService(String orderSort) {
        String keyword = txtSearchService.getText();
            listService.clear();
            listService = dao.getService(keyword, orderSort);
            showService(listService);
    }

    private void showGuest(List<Object[]> listGuest) {
        DefaultTableModel tableModel = (DefaultTableModel) tblGuest.getModel();
        tableModel.setRowCount(0);
        for (Object[] objects : listGuest) {
            tableModel.addRow(new Object[]{objects[0],objects[1],objects[2]});
        }
    }

    private void searchGuest() {
        String keyword = txtSearchGuest.getText();
           if(!keyword.isEmpty()) {
                listGuest.clear();
            listGuest = dao.getGuest(keyword);
            showGuest(listGuest);
           } else {
               MsgBox.showMessage(this, "Vui lòng nhập thông tin trước khi tìm");
           }
    }
}
